version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        USER_ID : 1000
        GROUP_ID : 1000
    working_dir: /src
    volumes: 
      - ./src:/src
    entrypoint: ['php']
  composer:
    image: composer:latest
    working_dir: /src
    volumes: 
      - ./src:/src

